fixing params error, basing on saghul/lxd-alpine-builder

diff --git a/build-alpine b/build-alpine
--- a/build-alpine
+++ b/build-alpine
@@ -2,7 +2,7 @@
 
 
 # Make sure the usual locations are in PATH
-PATH=/bin:/sbin:/usr/bin:/usr/sbin:$PATH
+PATH=$PATH:/usr/sbin:/usr/bin:/sbin:/bin
 export PATH
 
 key_sha256sums="9c102bcc376af1498d549b77bdbfa815ae86faa1d2d82f040e616b18ef2df2d4  alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
@@ -11,67 +11,46 @@ ebf31683b56410ecc4c00acd9f6e2839e237a3b62b5ae7ef686705c7ba0396a9  alpine-devel@l
 1bb2a846c0ea4ca9d0e7862f970863857fc33c32f5506098c636a62a726a847b  alpine-devel@lists.alpinelinux.org-524d27bb.rsa.pub
 12f899e55a7691225603d6fb3324940fc51cd7f133e7ead788663c2b7eecb00c  alpine-devel@lists.alpinelinux.org-5261cecb.rsa.pub"
 
-get_static_url(){
-    wget="wget -q -O -"
-    mirror_list=$(mktemp)
-    wget -q http://dl-cdn.alpinelinux.org/alpine/MIRRORS.txt -O "$mirror_list"
-
-    mirror_count=$(wc -l "$mirror_list" | cut -d " " -f 1)
-    random=$((RANDOM))
-    right_random=$(expr "$random" % "$mirror_count" + 1)
-  
-	  url=$(sed "$right_random"\!d "$mirror_list")
-    echo "Selected arch: $apk_arch"
-    echo "Selecting mirror: $url"
-    repo="$url"/latest-stable/main
-}
-
-get_informations(){
-    yaml_path=latest-stable/releases/"$apk_arch"/latest-releases.yaml
-    echo -n "Determining the latest release..."
-
-	  yaml_file=$(mktemp)
-	  wget -q "$url"/"$yaml_path" -O "$yaml_file"
-  
-	  release=$(cat "$yaml_file" |\
-		    grep branch | cut -d ':' -f 2 |\
-				cut -d ' ' -f 2 | uniq)
-
-    if [ -z "$release" ]; then
-		  echo "Couldn't get release!"
-      return 1
-    fi
-
-    echo "$release"
-
-    echo -n "Determining the latest version... "
-	  version=$(cat "$yaml_file" |\
-		    grep version | cut -d ':' -f 2 |\
-				cut -d ' ' -f 2 | uniq)
-
-	  if [ -z "$version" ]; then
-		  echo "Couldn't get version!"
-      return 1
-    fi
-
-    echo "$version"
-    rm -f "$yaml_file"
-}
 
 get_static_apk () {
-    pkglist=alpine-keys:apk-tools-static:alpine-mirrors
-    wget="$wget $repo/$apk_arch"
+    wget="wget -q -O -"
+    pkglist=alpine-keys:apk-tools-static
+    auto_repo_dir=
+
+    if [ -z "$repository" ]; then
+        url=http://dl-cdn.alpinelinux.org/alpine/
+	yaml_path="latest-stable/releases/$apk_arch/latest-releases.yaml"
+        if [ -z "$release" ]; then
+            echo -n "Determining the latest release... "
+            release=$($wget $url/$yaml_path | \
+	        awk '$1 == "branch:" {print $2; exit 0}')
+            if [ -z "$release" ]; then
+                release=$($wget $url/.latest.$apk_arch.txt | \
+                    cut -d " " -f 3 | cut -d / -f 1 | uniq)
+            fi
+            if [ -z "$release" ]; then
+                echo failed
+                return 1
+            fi
+            echo $release
+        fi
+        auto_repo_dir=$release/main
+        repository=$url/$auto_repo_dir
+        pkglist=$pkglist:alpine-mirrors
+    fi
+
+    echo "Using static apk from $repository/$apk_arch"
+    wget="$wget $repository/$apk_arch"
 
     # parse APKINDEX to find the current versions
     static_pkgs=$($wget/APKINDEX.tar.gz | \
         tar -Oxz APKINDEX | \
-        awk -F: -v pkglist="$pkglist" '
+        awk -F: -v pkglist=$pkglist '
             BEGIN { split(pkglist,pkg) }
             $0 != "" { f[$1] = $2 }
             $0 == "" { for (i in pkg)
                            if (pkg[i] == f["P"])
                                print(f["P"] "-" f["V"] ".apk") }')
-
     [ "$static_pkgs" ] || return 1
 
     mkdir -p "$rootfs" || return 1
@@ -85,27 +64,40 @@ get_static_apk () {
 
     # verify checksum of the key
     keyname=$(echo $rootfs/sbin/apk.static.*.pub | sed 's/.*\.SIGN\.RSA\.//')
-    checksum=$(echo "$key_sha256sums" | grep -w "$keyname")
+    checksum=$(echo "$key_sha256sums" |  grep -w "$keyname")
     if [ -z "$checksum" ]; then
         echo "ERROR: checksum is missing for $keyname"
         return 1
     fi
-    (cd "$rootfs"/etc/apk/keys && echo "$checksum" | sha256sum -c -) || return 1
+    (cd $rootfs/etc/apk/keys && echo "$checksum" | sha256sum -c -) || return 1
 
     # verify the static apk binary signature
-    APK="$rootfs"/sbin/apk.static
-    openssl dgst -sha1 -verify "$rootfs/etc/apk/keys/$keyname" \
+    APK=$rootfs/sbin/apk.static
+    openssl dgst -sha1 -verify $rootfs/etc/apk/keys/$keyname \
         -signature "$APK.SIGN.RSA.$keyname" "$APK" || return 1
+
+    if [ "$auto_repo_dir" ]; then
+        mirror_list=$rootfs/usr/share/alpine-mirrors/MIRRORS.txt
+
+        mkdir -p $rootfs/usr/share/alpine-mirrors/
+        wget http://alpine.mirror.wearetriple.com/MIRRORS.txt -O $rootfs/usr/share/alpine-mirrors/MIRRORS.txt
+
+        mirror_count=$(wc -l $mirror_list | cut -d " " -f 1)
+        random=$(hexdump -n 2 -e '/2 "%u"' /dev/urandom)
+        repository=$(sed $(expr $random % $mirror_count + 1)\!d \
+            $mirror_list)/$auto_repo_dir
+        echo "Selecting mirror $repository"
+    fi
 }
 
 install_alpine() {
     mkdir -p "$rootfs"/etc/apk || return 1
     : ${keys_dir:=/etc/apk/keys}
-    if ! [ -d "$rootfs/etc/apk/keys" ] && [ -d "$keys_dir" ]; then
+    if ! [ -d "$rootfs"/etc/apk/keys ] && [ -d "$keys_dir" ]; then
         cp -r "$keys_dir" "$rootfs"/etc/apk/keys
     fi
-    if [ -n "$repo" ]; then
-        echo "$repo" > "$rootfs"/etc/apk/repositories
+    if [ -n "$repository" ]; then
+        echo "$repository" > "$rootfs"/etc/apk/repositories
     else
         cp /etc/apk/repositories "$rootfs"/etc/apk/repositories || return 1
         if [ -n "$release" ]; then
@@ -113,8 +105,11 @@ install_alpine() {
                 "$rootfs"/etc/apk/repositories
         fi
     fi
-    bash="bash bash-doc bash-completion"
-    $APK add -U --initdb --root $rootfs --arch $apk_arch $bash "$@" alpine-base
+    opt_arch=
+    if [ -n "$apk_arch" ]; then
+        opt_arch="--arch $apk_arch"
+    fi
+    $APK add -U --initdb --root $rootfs $opt_arch "$@" alpine-base
 }
 
 configure_alpine() {
@@ -127,37 +122,12 @@ configure_alpine() {
 EOF
 
     # configure the network using dhcp
-    cat <<EOF > "$rootfs"/etc/network/interfaces
+    cat <<EOF > $rootfs/etc/network/interfaces
 auto lo
 iface lo inet loopback
 
 auto eth0
 iface eth0 inet dhcp
-EOF
-
-        # Configure the network using dhcp
-    cat <<EOF > "$rootfs"/etc/network/interfaces
-auto lo
-iface lo inet loopback
-
-auto eth0
-iface eth0 inet dhcp
-EOF
-
-    cat << EOF > "$rootfs"/etc/network/hostname
-alpine
-EOF
-
-    cat << EOF > "$rootfs"/etc/hosts
-127.0.0.1   localhost
-127.0.1.1   alpine.local
-
-# The following lines are desirable for IPv6 capable hosts
-::1     ip6-localhost ip6-loopback
-fe00::0 ip6-localnet
-ff00::0 ip6-mcastprefix
-ff02::1 ip6-allnodes
-ff02::2 ip6-allrouters
 EOF
 
     # start services
@@ -166,8 +136,8 @@ EOF
     ln -s /etc/init.d/syslog "$rootfs"/etc/runlevels/boot/syslog
 
     # cleanup
-    rm -rf "$rootfs"/var/cache/apk/*
-    rm -f "$rootfs"/sbin/apk.static*
+    rm -rf "$rootfs/var/cache/apk"/*
+    rm -f "$rootfs/sbin"/apk.static*
 
     return 0
 }
@@ -178,15 +148,29 @@ create_metadata() {
 
     cat <<EOF > metadata.yaml
 {
-    "architecture": "$apk_arch",
+    "architecture": "$arch",
     "creation_date": $release_epoch,
     "properties": {
-        "architecture": "$apk_arch",
+        "architecture": "$arch",
         "description": "alpine $release ($release_date)",
         "name": "alpine-$release-$release_date",
         "os": "alpine",
         "release": "$release",
         "variant": "default"
+    },
+    "templates": {
+        "/etc/hostname": {
+            "template": "hostname.tpl",
+            "when": [
+                "create"
+            ]
+        },
+        "/etc/hosts": {
+            "template": "hosts.tpl",
+            "when": [
+                "create"
+            ]
+        }
     }
 }
 EOF
@@ -200,6 +184,7 @@ EOF
     cat <<EOF > templates/hosts.tpl
 127.0.0.1   localhost
 127.0.1.1   {{ container.name }}
+
 # The following lines are desirable for IPv6 capable hosts
 ::1     ip6-localhost ip6-loopback
 fe00::0 ip6-localnet
@@ -213,23 +198,12 @@ EOF
 
 package_image() {
     release_date=$(date +%Y%m%d_%H%M)
-    lxd_alpine=lxd-alpine-${release}-${arch}-${release_date}.tar.gz
-    docker_alpine=docker-alpine-${release}-${arch}-${release_date}.tar.gz
 
-    (cd "$rootfs"; tar -zcf ../"$docker_alpine" --numeric-owner *)
-    tar -zcf $lxd_alpine --numeric-owner metadata.yaml templates rootfs
+    (cd "$rootfs" && tar -zcf docker-alpine-$release-$arch-$release_date.tar.gz --numeric-owner *)
+    tar -zcf lxd-alpine-$release-$arch-$release_date.tar.gz --numeric-owner metadata.yaml templates rootfs
     rm -f metadata.yaml
     rm -rf templates
     rm -rf rootfs
-}
-
-setup_dockerfile(){
-  cat <<EOF > Dockerfile
-FROM scratch
-ADD $docker_alpine /
-CMD ["/bin/bash"]
-EOF
-  echo "Dockerfile done!"
 }
 
 die() {
@@ -238,29 +212,30 @@ die() {
 }
 
 usage() {
-  cat >&2 <<EOF
-Alpine Builder for LXD and DOCKER.
-Usage: $(basename $0) [-h|--help] [-r|--release <version>] [-a|--arch <arch>] [ <app to install (like zsh)> ]
-Supported archs: aarch64
-                x86
-                x86_64
-                armhf
+    cat >&2 <<EOF
+Usage: $(basename $0) [-h|--help] [-r|--repository <url>]
+                   [-R|--release <release>] [-a|--arch <arch>]
+                   [PKG...]
 EOF
-  return 1
 }
 
+usage_err() {
+    usage
+    exit 1
+}
 
 rootfs="$(pwd)/rootfs"
 release=
-to_install=
+arch=$(uname -m)
 
+# template requires root
 if [ $(id -u) -ne 0 ]; then
    echo "$(basename $0): must be run as root" >&2
    exit 1
 fi
 
-options=$(getopt -o h:r:R:a: -l help,release:,arch: -- "$@")
-[ $? -eq 0 ] || usage
+options=$(getopt -o h:r:R:a: -l help,repository:,release:,arch: -- "$@")
+[ $? -eq 0 ] || usage_err
 eval set -- "$options"
 
 while [ $# -gt 0 ]; do
@@ -268,54 +243,53 @@ while [ $# -gt 0 ]; do
     -h|--help)
         usage
         exit 0
-				;;
-    -r|--release)
-        release="$2"
+        ;;
+    -r|--repository)
+        repository=$2
+	;;
+    -R|--release)
+        release=$2
         ;;
     -a|--arch)
-        arch="$2"
-        ;;
-      *)
-          to_install="$to_install $1"
+        arch=$2
         ;;
     --)
-        break;
+	shift
+        break;;
     esac
+    shift 2
 done
 
+
+if [ -z "$rootfs" ]; then
+    rootfs="$(pwd)/rootfs"
+fi
+
+apk_arch=$arch
+
 case "$arch" in
-    aarch64)
+    i[3-6]86)
+        apk_arch=x86
         ;;
-			x64)
-				arch=aarch64
-				;;
     x86)
         ;;
-    x86_64 | "")
-        arch=x86_64
+    x86_64|"")
         ;;
     arm*)
-        arch=armhf
+        apk_arch=armhf
         ;;
     *)
-        die "Unsupported architecture: $arch"
-				usage
+        die "unsupported architecture: $arch"
         ;;
 esac
 
-apk_arch="$arch"
-
 : ${APK:=apk}
 if ! which $APK >/dev/null; then
-    get_static_url || die "Failed to get a valid url"
-    get_informations || exit 1
     get_static_apk || die "Failed to download a valid static apk"
 fi
 
-install_alpine "$to_install" || die "Failed to install rootfs"
+install_alpine "$@" || die "Failed to install rootfs"
 configure_alpine || die "Failed to configure rootfs"
 create_metadata || die "Failed to create metadata"
 package_image || die "Failed to package image"
-setup_dockerfile || die "Failed to setup Dockerfile"
 
-chmod a=rw $docker_alpine $lxd_alpine Dockerfile
